services:
  qdrant:
    image: qdrant/qdrant:v1.9.4
    container_name: qdrant
    environment:
      QDRANT__SERVICE__HOST: '0.0.0.0'
      QDRANT__SERVICE__HTTP_PORT: '6333'
      QDRANT__SERVICE__GRPC_PORT: '6334'
      QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API_KEY} 
    volumes:
      - /opt/apps/persistence/qdrant:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - "6333"      # Internally makes port 6333 available to other containers
      - "6334"      # Internally makes port 6334 available to other containers
      # - "6335"      # Internally makes port 6335 available to other containers   
    networks:
      - qdrant_network
    restart: unless-stopped

  # vector-admin:
  #   image: mintplexlabs/vectoradmin:latest
  #   container_name: vector-admin
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     SERVER_PORT: '3001'
  #     DATABASE_CONNECTION_STRING: ${VECTOR_ADMIN_DATABASE_URL-postgresql://vectoradmin:password@postgres:5432/vdbms}
  #   env_file:
  #     - .env
  #   networks:
  #     - qdrant_network
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: vector-admin-db
  #   volumes:
  #     - /opt/databases/prod/vector-admin-db/postgresql/data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: vectoradmin
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: vdbms
  #   networks:
  #     - qdrant_network
  #   restart: unless-stopped
  #
networks:
  qdrant_network:
    driver: bridge
